/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppraisalCycle {
  'id' : string,
  'title' : string,
  'endDate' : string,
  'cycleType' : string,
  'evaluationCriteria' : string,
  'pdfUrl' : string,
  'batch' : string,
  'answerSheetAnalysisId' : string,
  'resultsUrl' : string,
  'startDate' : string,
}
export interface Batch {
  'courseMaterialCollectionId' : string,
  'name' : string,
  'streamId' : string,
  'appraisalCycleId' : string,
}
export interface CourseMaterial {
  'id' : string,
  'originalFileName' : string,
  'title' : string,
  'fileSize' : bigint,
  'batch' : string,
  'uploadDate' : bigint,
  'uploadedBy' : string,
  'fileUrl' : string,
}
export interface EducationalResource {
  'id' : string,
  'accessLevel' : string,
  'title' : string,
  'content' : string,
  'file' : ExternalBlob,
  'downloadUrl' : string,
  'fileSize' : bigint,
  'resourceType' : string,
  'batch' : string,
  'pdfId' : string,
  'uploadDate' : bigint,
  'uploadedBy' : string,
}
export type ExternalBlob = Uint8Array;
export interface GeneralDocument {
  'id' : string,
  'accessLevel' : string,
  'originalFileName' : string,
  'title' : string,
  'documentType' : string,
  'fileSize' : bigint,
  'uploadDate' : bigint,
  'uploadedBy' : string,
  'fileUrl' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBatch' : ActorMethod<[string, string, string, string], boolean>,
  'deleteAppraisalCycle' : ActorMethod<[string], boolean>,
  'deleteCourseMaterial' : ActorMethod<[string], boolean>,
  'deleteEducationalResource' : ActorMethod<[string], boolean>,
  'deleteGeneralDocument' : ActorMethod<[string], boolean>,
  'getAppraisalCyclesByBatch' : ActorMethod<[string], Array<AppraisalCycle>>,
  'getBatch' : ActorMethod<[string], Batch>,
  'getCourseMaterialsByBatch' : ActorMethod<[string], Array<CourseMaterial>>,
  'getEducationalResources' : ActorMethod<[string], Array<EducationalResource>>,
  'getGeneralDocumentsByType' : ActorMethod<[string], Array<GeneralDocument>>,
  'listBatches' : ActorMethod<[], Array<Batch>>,
  'uploadFileToCourseMaterial' : ActorMethod<
    [string, string, string, bigint, string, string, ExternalBlob],
    string
  >,
  'uploadFileToEducationalResource' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      ExternalBlob,
    ],
    string
  >,
  'uploadFileToGeneralDocument' : ActorMethod<
    [string, string, string, bigint, string, string, string, ExternalBlob],
    string
  >,
  'validateBatch' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];