/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AppraisalCycle = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'endDate' : IDL.Text,
  'cycleType' : IDL.Text,
  'evaluationCriteria' : IDL.Text,
  'pdfUrl' : IDL.Text,
  'batch' : IDL.Text,
  'answerSheetAnalysisId' : IDL.Text,
  'resultsUrl' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Batch = IDL.Record({
  'courseMaterialCollectionId' : IDL.Text,
  'name' : IDL.Text,
  'streamId' : IDL.Text,
  'appraisalCycleId' : IDL.Text,
});
export const CourseMaterial = IDL.Record({
  'id' : IDL.Text,
  'originalFileName' : IDL.Text,
  'title' : IDL.Text,
  'fileSize' : IDL.Nat,
  'batch' : IDL.Text,
  'uploadDate' : IDL.Int,
  'uploadedBy' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EducationalResource = IDL.Record({
  'id' : IDL.Text,
  'accessLevel' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'file' : ExternalBlob,
  'downloadUrl' : IDL.Text,
  'fileSize' : IDL.Nat,
  'resourceType' : IDL.Text,
  'batch' : IDL.Text,
  'pdfId' : IDL.Text,
  'uploadDate' : IDL.Int,
  'uploadedBy' : IDL.Text,
});
export const GeneralDocument = IDL.Record({
  'id' : IDL.Text,
  'accessLevel' : IDL.Text,
  'originalFileName' : IDL.Text,
  'title' : IDL.Text,
  'documentType' : IDL.Text,
  'fileSize' : IDL.Nat,
  'uploadDate' : IDL.Int,
  'uploadedBy' : IDL.Text,
  'fileUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBatch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteAppraisalCycle' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCourseMaterial' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEducationalResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteGeneralDocument' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAppraisalCyclesByBatch' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AppraisalCycle)],
      ['query'],
    ),
  'getBatch' : IDL.Func([IDL.Text], [Batch], ['query']),
  'getCourseMaterialsByBatch' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CourseMaterial)],
      ['query'],
    ),
  'getEducationalResources' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EducationalResource)],
      ['query'],
    ),
  'getGeneralDocumentsByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GeneralDocument)],
      ['query'],
    ),
  'listBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
  'uploadFileToCourseMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'uploadFileToEducationalResource' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ExternalBlob,
      ],
      [IDL.Text],
      [],
    ),
  'uploadFileToGeneralDocument' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
      ],
      [IDL.Text],
      [],
    ),
  'validateBatch' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AppraisalCycle = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'endDate' : IDL.Text,
    'cycleType' : IDL.Text,
    'evaluationCriteria' : IDL.Text,
    'pdfUrl' : IDL.Text,
    'batch' : IDL.Text,
    'answerSheetAnalysisId' : IDL.Text,
    'resultsUrl' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Batch = IDL.Record({
    'courseMaterialCollectionId' : IDL.Text,
    'name' : IDL.Text,
    'streamId' : IDL.Text,
    'appraisalCycleId' : IDL.Text,
  });
  const CourseMaterial = IDL.Record({
    'id' : IDL.Text,
    'originalFileName' : IDL.Text,
    'title' : IDL.Text,
    'fileSize' : IDL.Nat,
    'batch' : IDL.Text,
    'uploadDate' : IDL.Int,
    'uploadedBy' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EducationalResource = IDL.Record({
    'id' : IDL.Text,
    'accessLevel' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'file' : ExternalBlob,
    'downloadUrl' : IDL.Text,
    'fileSize' : IDL.Nat,
    'resourceType' : IDL.Text,
    'batch' : IDL.Text,
    'pdfId' : IDL.Text,
    'uploadDate' : IDL.Int,
    'uploadedBy' : IDL.Text,
  });
  const GeneralDocument = IDL.Record({
    'id' : IDL.Text,
    'accessLevel' : IDL.Text,
    'originalFileName' : IDL.Text,
    'title' : IDL.Text,
    'documentType' : IDL.Text,
    'fileSize' : IDL.Nat,
    'uploadDate' : IDL.Int,
    'uploadedBy' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBatch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteAppraisalCycle' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCourseMaterial' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEducationalResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteGeneralDocument' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAppraisalCyclesByBatch' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AppraisalCycle)],
        ['query'],
      ),
    'getBatch' : IDL.Func([IDL.Text], [Batch], ['query']),
    'getCourseMaterialsByBatch' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CourseMaterial)],
        ['query'],
      ),
    'getEducationalResources' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EducationalResource)],
        ['query'],
      ),
    'getGeneralDocumentsByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GeneralDocument)],
        ['query'],
      ),
    'listBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
    'uploadFileToCourseMaterial' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
        ],
        [IDL.Text],
        [],
      ),
    'uploadFileToEducationalResource' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ExternalBlob,
        ],
        [IDL.Text],
        [],
      ),
    'uploadFileToGeneralDocument' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
        ],
        [IDL.Text],
        [],
      ),
    'validateBatch' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };