/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GeneralDocument {
    id: string;
    accessLevel: string;
    originalFileName: string;
    title: string;
    documentType: string;
    fileSize: bigint;
    uploadDate: bigint;
    uploadedBy: string;
    fileUrl: string;
}
export interface CourseMaterial {
    id: string;
    originalFileName: string;
    title: string;
    fileSize: bigint;
    batch: string;
    uploadDate: bigint;
    uploadedBy: string;
    fileUrl: string;
}
export interface AppraisalCycle {
    id: string;
    title: string;
    endDate: string;
    cycleType: string;
    evaluationCriteria: string;
    pdfUrl: string;
    batch: string;
    answerSheetAnalysisId: string;
    resultsUrl: string;
    startDate: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface EducationalResource {
    id: string;
    accessLevel: string;
    title: string;
    content: string;
    file: ExternalBlob;
    downloadUrl: string;
    fileSize: bigint;
    resourceType: string;
    batch: string;
    pdfId: string;
    uploadDate: bigint;
    uploadedBy: string;
}
export interface Batch {
    courseMaterialCollectionId: string;
    name: string;
    streamId: string;
    appraisalCycleId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addBatch(name: string, streamId: string, courseMaterialCollectionId: string, appraisalCycleId: string): Promise<boolean>;
    deleteAppraisalCycle(id: string): Promise<boolean>;
    deleteCourseMaterial(id: string): Promise<boolean>;
    deleteEducationalResource(id: string): Promise<boolean>;
    deleteGeneralDocument(id: string): Promise<boolean>;
    getAppraisalCyclesByBatch(batch: string): Promise<Array<AppraisalCycle>>;
    getBatch(name: string): Promise<Batch>;
    getCourseMaterialsByBatch(batch: string): Promise<Array<CourseMaterial>>;
    getEducationalResources(resourceType: string): Promise<Array<EducationalResource>>;
    getGeneralDocumentsByType(documentType: string): Promise<Array<GeneralDocument>>;
    listBatches(): Promise<Array<Batch>>;
    uploadFileToCourseMaterial(title: string, batch: string, fileUrl: string, fileSize: bigint, uploadedBy: string, originalFileName: string, blob: ExternalBlob): Promise<string>;
    uploadFileToEducationalResource(title: string, resourceType: string, accessLevel: string, content: string, batch: string, downloadUrl: string, pdfId: string, uploadedBy: string, fileSize: bigint, blob: ExternalBlob): Promise<string>;
    uploadFileToGeneralDocument(title: string, documentType: string, fileUrl: string, fileSize: bigint, uploadedBy: string, accessLevel: string, originalFileName: string, blob: ExternalBlob): Promise<string>;
    validateBatch(selectedBatch: string): Promise<boolean>;
}
import type { EducationalResource as _EducationalResource, ExternalBlob as _ExternalBlob, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addBatch(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addBatch(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBatch(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteAppraisalCycle(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppraisalCycle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppraisalCycle(arg0);
            return result;
        }
    }
    async deleteCourseMaterial(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourseMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourseMaterial(arg0);
            return result;
        }
    }
    async deleteEducationalResource(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEducationalResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEducationalResource(arg0);
            return result;
        }
    }
    async deleteGeneralDocument(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGeneralDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGeneralDocument(arg0);
            return result;
        }
    }
    async getAppraisalCyclesByBatch(arg0: string): Promise<Array<AppraisalCycle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppraisalCyclesByBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppraisalCyclesByBatch(arg0);
            return result;
        }
    }
    async getBatch(arg0: string): Promise<Batch> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatch(arg0);
            return result;
        }
    }
    async getCourseMaterialsByBatch(arg0: string): Promise<Array<CourseMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseMaterialsByBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseMaterialsByBatch(arg0);
            return result;
        }
    }
    async getEducationalResources(arg0: string): Promise<Array<EducationalResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEducationalResources(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEducationalResources(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGeneralDocumentsByType(arg0: string): Promise<Array<GeneralDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGeneralDocumentsByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGeneralDocumentsByType(arg0);
            return result;
        }
    }
    async listBatches(): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBatches();
            return result;
        }
    }
    async uploadFileToCourseMaterial(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFileToCourseMaterial(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFileToCourseMaterial(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async uploadFileToEducationalResource(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: bigint, arg9: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFileToEducationalResource(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFileToEducationalResource(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async uploadFileToGeneralDocument(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFileToGeneralDocument(arg0, arg1, arg2, arg3, arg4, arg5, arg6, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFileToGeneralDocument(arg0, arg1, arg2, arg3, arg4, arg5, arg6, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async validateBatch(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateBatch(arg0);
            return result;
        }
    }
}
async function from_candid_EducationalResource_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationalResource): Promise<EducationalResource> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    accessLevel: string;
    title: string;
    content: string;
    file: _ExternalBlob;
    downloadUrl: string;
    fileSize: bigint;
    resourceType: string;
    batch: string;
    pdfId: string;
    uploadDate: bigint;
    uploadedBy: string;
}): Promise<{
    id: string;
    accessLevel: string;
    title: string;
    content: string;
    file: ExternalBlob;
    downloadUrl: string;
    fileSize: bigint;
    resourceType: string;
    batch: string;
    pdfId: string;
    uploadDate: bigint;
    uploadedBy: string;
}> {
    return {
        id: value.id,
        accessLevel: value.accessLevel,
        title: value.title,
        content: value.content,
        file: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.file),
        downloadUrl: value.downloadUrl,
        fileSize: value.fileSize,
        resourceType: value.resourceType,
        batch: value.batch,
        pdfId: value.pdfId,
        uploadDate: value.uploadDate,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EducationalResource>): Promise<Array<EducationalResource>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EducationalResource_n9(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
